search_jobs:
  description: >
    Use the JobSpy Job Search Tool to search for job listings. Call the tool with the following parameters:
    - site_name: Use the default job sites (indeed, linkedin, glassdoor)
    - search_term: Use the search_term from the provided job search parameters
    - location: Use the location from the provided job search parameters
    - results_wanted: Use the results_wanted from the provided job search parameters
    - hours_old: Use 72 hours for recent postings
    - country_indeed: Use "USA" as the country
    - is_remote: Use the is_remote flag from the provided job search parameters
    
    The tool will search across multiple job boards and return relevant job listings that match
    the user's career profile and search criteria.
  expected_output: >
    A list of relevant job listings with detailed information including:
    - Job title and company
    - Required skills and qualifications
    - Job description
    - Location and salary range (if available)
    - Remote work availability (if applicable)

analyze_skills_gap:
  description: >
    Analyze the gap between the user's current skills and the requirements of found job listings.
    Identify which skills the user already has that match job requirements and which skills are missing.
    Prioritize the most important skill gaps based on frequency across job listings.
  expected_output: >
    A detailed skills analysis report including:
    - Matching skills between user profile and job requirements
    - Missing skills and their importance
    - Recommendations for skill development
    - Job-specific skill alignment scores

filter_jobs:
  description: >
    Filter and refine the initial job search results based on the user's specific preferences and fine-tune criteria.
    Use the fine_tune_search_string from job_search_params to analyze each job listing for relevance and fit.
    If fine_tune_search_string is provided, apply it as additional filtering criteria.
    If no fine_tune_search_string is provided, simply pass through the original job listings with basic ranking.
    Analyze job descriptions, company culture mentions, benefits, and work environment details.
  expected_output: >
    A filtered and ranked list of job listings that includes:
    - Original job listings that match the fine-tune criteria (if provided)
    - Relevance score for each job (1-10 scale) based on fine-tune criteria
    - Explanation of why each job matches or doesn't match the fine-tune criteria
    - Final recommended job listings sorted by relevance score
    - If no fine-tune criteria provided, return all jobs with basic relevance scoring

generate_resume:
  description: >
    Create a personalized resume tailored to the analyzed job requirements.
    Use the user's career information and emphasize skills that match job requirements.
    Format the resume to be ATS-friendly and highlight relevant experience.
  expected_output: >
    A professionally formatted resume document that includes:
    - Contact information and professional summary
    - Skills section highlighting relevant technical and soft skills
    - Experience section with quantified achievements
    - Education and certifications
    - ATS-optimized formatting and keywords